

GET https://arpa3e2b3l.execute-api.us-east-1.amazonaws.com/prod/spaces
###

POST https://jnaqmy83ib.execute-api.us-east-1.amazonaws.com/prod/spaces
content-type: application/json

{
    "location": "Orlando",
    "name": "Best football"
}
###

PUT https://jnaqmy83ib.execute-api.us-east-1.amazonaws.com/prod/spaces?id=c000461d-19df-493c-b629-e2a349540f6d
content-type: application/json

{
    "name": "Best HHH"
}
###

DELETE https://jnaqmy83ib.execute-api.us-east-1.amazonaws.com/prod/spaces?id=c000461d-19df-493c-b629-e2a349540f6d
###


GET https://jnaqmy83ib.execute-api.us-east-1.amazonaws.com/prod/spaces?id=c000461d-19df-493c-b629-e2a349540f6d
###