

GET https://arpa3e2b3l.execute-api.us-east-1.amazonaws.com/prod/spaces
###

POST https://jnaqmy83ib.execute-api.us-east-1.amazonaws.com/prod/spaces
content-type: application/json

{
    "location": "Paris"
}
###

GET https://jnaqmy83ib.execute-api.us-east-1.amazonaws.com/prod/spaces